sudo: false
language: perl
matrix:
    fast_finish: true
perl:
   - '5.24'
   - '5.14'
before_install:
   - git config --global user.name "TravisCI"
   - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
install:
   - cpanm --quiet --notest --skip-satisfied -l /home/git/regentmarkets/cpan/local Dist::Zilla Dist::Zilla::App::Command::cover App::cpm
   - cpm install -L /home/git/regentmarkets/cpan/local -w 2 --mirror=http://cpan.cpantesters.org/ $(dzil authordeps --missing)
   - cpm install -L /home/git/regentmarkets/cpan/local -w 2 --mirror=http://cpan.cpantesters.org/ $(dzil listdeps --author --missing)
   - cpanm --quiet --notest https://cpan.metacpan.org/authors/id/S/SR/SRI/Mojolicious-7.29.tar.gz https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.30.tar.gz

script:
   - dzil smoke --release --author && dzil cover -test -report codecov && dzil xtest

