---
abstract: 'WebSocket proxy for JSON-RPC 2.0 server'
author:
  - 'binary.com <BINARY@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Path::Tiny: '0'
  Test::CheckDeps: '0.010'
  Test::Fatal: '0'
  Test::MockModule: '0'
  Test::MockObject: '0'
  Test::Mojo: '0'
  Test::More: '0.98'
  Test::Simple: '0.44'
  Test::TCP: '0'
  perl: '5.014000'
configure_requires:
  ExtUtils::MakeMaker: '7.1101'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojo-WebSocketProxy
requires:
  Class::Method::Modifiers: '0'
  Data::UUID: '0'
  DataDog::DogStatsd::Helper: '0.05'
  Future: '0.36'
  Future::Mojo: '0.004'
  IO::Async::Loop::Mojo: '0'
  JSON::MaybeUTF8: '0'
  Job::Async: '0'
  Mojo::Redis2: '0'
  MojoX::JSON::RPC: '0'
  Mojolicious: '7.29'
  Scalar::Util: '0'
  Syntax::Keyword::Try: '0.04'
  Unicode::Normalize: '1.25'
  curry: '1.001'
  indirect: '0'
  perl: '5.014000'
resources:
  bugtracker: https://github.com/binary-com/perl-Mojo-WebSocketProxy/issues
  repository: git://github.com/binary-com/perl-Mojo-WebSocketProxy.git
version: '0.13'
x_generated_by_perl: v5.26.2
x_serialization_backend: 'YAML::Tiny version 1.73'
